version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, python]
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    cooldown:
      default-days: 7
    groups:
      development-dependencies:
        dependency-type: development
        update-types: [minor, patch]
      production-dependencies:
        dependency-type: production
        update-types: [minor, patch]
